function hFig = create_model_architecture_figure(figDir)
%CREATE_MODEL_ARCHITECTURE_FIGURE
% Minimal schematic Figure 1 for the democracy/autocracy model.
%
% This is intentionally not a full causal graph. It shows the two sides of the
% model and the external inputs. Equations and coefficients are in the Methods.

    if nargin < 1 || isempty(figDir)
        figDir = 'I:\democracy_autocracy\figures';
    end

    if ~exist(figDir, 'dir')
        mkdir(figDir);
    end

   hFig = figure('Color','w', ...
        'Name','Model architecture', ...
        'Units','pixels', ...
        'Position',[100 100 750 520]);

    ax = axes('Position',[0.035 0.035 0.93 0.93]);
    hold(ax,'on');
    axis(ax,[0 1 0 1]);
    axis(ax,'off');

    % ---------------------------------------------------------------------
    % Layout
    leftBox   = [0.06 0.43 0.36 0.49];
    rightBox  = [0.58 0.43 0.36 0.49];
    stressBox = [0.33 0.13 0.28 0.13];
    shockBox  = [0.70 0.13 0.18 0.13];  

    % ---------------------------------------------------------------------
    % Main modules
    draw_module(ax, leftBox, ...
        'Democratic stabilizing side', ...
        { ...
        '$N_t$: norm compliance', ...
        '$D_t$: institutional strength', ...
        '$B^{\mathrm{dem}}_t=N_tD_t$', ...
        '$S_t=D_t(1-E_t)$' ...
        });

    draw_module(ax, rightBox, ...
        'Autocratic reinforcing side', ...
        { ...
        '$E_t$: elite autocratic pressure', ...
        '$P_t$: polarization', ...
        '$B^{\mathrm{aut}}_t=E_tP_t$' ...
        });

    draw_small_box(ax, stressBox, '$u_t$', 'exogenous stress');
    draw_small_box(ax, shockBox, '$\xi_t$', 'shock magnitude');

    % ---------------------------------------------------------------------
    % Cross-module relations
    arrow(ax, 0.42, 0.72, 0.58, 0.72, '--');
    text(0.50, 0.755, 'constrains', ...
        'HorizontalAlignment','center', ...
        'FontName','Times New Roman', ...
        'FontSize',12);

    arrow(ax, 0.58, 0.61, 0.42, 0.61, '--');
    text(0.50, 0.575, 'weakens', ...
        'HorizontalAlignment','center', ...
        'FontName','Times New Roman', ...
        'FontSize',12);

    % ---------------------------------------------------------------------
    % External inputs
    arrow(ax, 0.42, 0.26, 0.25, 0.425, '-');
    text(0.30, 0.32, 'reduces', ...
        'HorizontalAlignment','center', ...
        'FontName','Times New Roman', ...
        'FontSize',12);

    arrow(ax, 0.5, 0.26, 0.75, 0.425, '-');
    text(0.66, 0.32, 'increases', ...
        'HorizontalAlignment','center', ...
        'FontName','Times New Roman', ...
        'FontSize',12);

    arrow(ax, 0.79, 0.26, 0.79, 0.425, '-');
    text(0.815, 0.345, 'increases', ...
        'HorizontalAlignment','left', ...
        'FontName','Times New Roman', ...
        'FontSize',12);
    
    % ---------------------------------------------------------------------
    % Footer
    text(0.50, 0.035, ...
        'Schematic only. Full update equations and coefficients are given in the Methods.', ...
        'HorizontalAlignment','center', ...
        'FontName','Times New Roman', ...
        'FontSize',12);

    % ---------------------------------------------------------------------
    % Export
    outBase = fullfile(figDir, 'figure1_model_architecture');

    set(hFig, 'PaperPositionMode','auto');
    print(hFig, [outBase '.pdf'], '-dpdf', '-painters');
    print(hFig, [outBase '.png'], '-dpng', '-r300');
end

function draw_module(ax, pos, titleStr, lines)

    rectangle(ax, ...
        'Position',pos, ...
        'Curvature',0.04, ...
        'FaceColor',[0.94 0.94 0.94], ...
        'EdgeColor',[0 0 0], ...
        'LineWidth',1.0);

    x = pos(1);
    y = pos(2);
    w = pos(3);
    h = pos(4);

    text(x+w/2, y+h-0.07, titleStr, ...
        'HorizontalAlignment','center', ...
        'Interpreter','none', ...
        'FontName','Times New Roman', ...
        'FontSize',14, ...
        'FontWeight','bold');

    y0 = y+h-0.17;
    dy = 0.075;

    for i = 1:numel(lines)
        text(x+w/2, y0-(i-1)*dy, lines{i}, ...
            'HorizontalAlignment','center', ...
            'Interpreter','latex', ...
            'FontName','Times New Roman', ...
            'FontSize',12);
    end
end

function draw_small_box(ax, pos, symbolStr, labelStr)

    rectangle(ax, ...
        'Position',pos, ...
        'Curvature',0.04, ...
        'FaceColor',[0.94 0.94 0.94], ...
        'EdgeColor',[0 0 0], ...
        'LineWidth',1.0);

    x = pos(1);
    y = pos(2);
    w = pos(3);
    h = pos(4);

    text(x+w/2, y+h*0.63, symbolStr, ...
        'HorizontalAlignment','center', ...
        'Interpreter','latex', ...
        'FontName','Times New Roman', ...
        'FontSize',13);

    text(x+w/2, y+h*0.30, labelStr, ...
        'HorizontalAlignment','center', ...
        'Interpreter','none', ...
        'FontName','Times New Roman', ...
        'FontSize',12);
end

function arrow(ax, x1, y1, x2, y2, lineStyle)

    plot(ax, [x1 x2], [y1 y2], ...
        'k', ...
        'LineStyle',lineStyle, ...
        'LineWidth',1.5);

    % Arrowhead
    dx = x2 - x1;
    dy = y2 - y1;
    L = sqrt(dx^2 + dy^2);

    if L == 0
        return
    end

    ux = dx / L;
    uy = dy / L;

    headLength = 0.020;
    headWidth  = 0.012;

    px = -uy;
    py = ux;

    p1 = [x2, y2];
    p2 = [x2 - headLength*ux + headWidth*px, ...
          y2 - headLength*uy + headWidth*py];
    p3 = [x2 - headLength*ux - headWidth*px, ...
          y2 - headLength*uy - headWidth*py];

    patch(ax, [p1(1) p2(1) p3(1)], [p1(2) p2(2) p3(2)], ...
        'k', ...
        'EdgeColor','k');
end