function x1 = step_model_local(x, u, shock, P)

    N   = x(1);
    E   = x(2);
    D   = x(3);
    Pol = x(4);

    S = D * (1 - E);
    demBloc = N * D;
    autBloc = E * Pol;

    zN = P.thetaN ...
       + P.aND    * D ...
       - P.aNE    * E ...
       - P.aNP    * Pol ...
       + P.aNN    * (N - 0.5) ...
       + P.aNS    * S ...
       - P.aNU    * u ...
       + P.aNdem  * demBloc ...
       - P.aNaut  * autBloc;

    zE = P.thetaE ...
       + P.aEP    * Pol ...
       + P.aEN    * (1 - N) ...
       + P.aED    * (1 - D) ...
       + P.aEE    * (E - 0.5) ...
       - P.aEnegD * D ...
       + P.aEU    * u ...
       - P.aEdem  * demBloc ...
       + P.aEaut  * autBloc;

    zD = P.thetaD ...
       + P.aDN    * N ...
       - P.aDE    * E ...
       - P.aDP    * Pol ...
       + P.aDD    * (D - 0.5) ...
       - P.aDU    * u ...
       + P.aDdem  * demBloc ...
       - P.aDaut  * autBloc;

    zP = P.thetaP ...
       + P.aPE     * E ...
       + P.aPnegD  * (1 - D) ...
       - P.aPN     * N ...
       + P.aPP     * (Pol - 0.5) ...
       + P.aPU     * u ...
       + P.aPshock * shock ...
       - P.aPdem   * demBloc ...
       + P.aPaut   * autBloc;

    target = 1 ./ (1 + exp(-[zN zE zD zP]));
    x1 = (1 - P.lam) .* x + P.lam .* target;
    x1 = min(max(x1,0),1);
end