function spec = default_scan_spec(baseP)
%DEFAULT_SCAN_SPEC
% Focused exploratory scan around the current baseline.
%
% mode:
%   'mult' = multiply baseline value by a sampled factor in [low, high]
%   'abs'  = sample directly from [low, high]

    spec = struct();

    spec.names = { ...
        'aNdem','aNaut', ...
        'aDdem','aDaut', ...
        'aEdem','aEaut', ...
        'aPdem','aPaut', ...
        'aNU','aEU','aDU','aPU', ...
        'uMax'};

    spec.mode = { ...
        'mult','mult', ...
        'mult','mult', ...
        'mult','mult', ...
        'mult','mult', ...
        'mult','mult','mult','mult', ...
        'mult'};

    % factors relative to baseline
    spec.low  = [ ...
        0.70, 0.70, ...
        0.70, 0.70, ...
        0.70, 0.70, ...
        0.70, 0.70, ...
        0.75, 0.75, 0.75, 0.75, ...
        0.75];

    spec.high = [ ...
        1.30, 1.30, ...
        1.30, 1.30, ...
        1.30, 1.30, ...
        1.30, 1.30, ...
        1.25, 1.25, 1.25, 1.25, ...
        1.25];

    % store baseline values for convenience
    baseVals = nan(1, numel(spec.names));
    for k = 1:numel(spec.names)
        baseVals(k) = baseP.(spec.names{k});
    end
    spec.baseVals = baseVals;
end